apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      containers:
      - image: bitnami/redis
        name: redis
        envFrom:
          - secretRef:
              name: redis-secret
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: /data
            name: redis-data
        resources: {}
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data

