
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # do what we did in configs + this !
  - ../configs/

patchesStrategicMerge:
  - ./pinger/deployment.yaml
  - ./poller/deployment.yaml


namespace: epsagon